//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.03 at 09:04:34 AM EDT 
//


package com.vw.formhandler.webspring.mvc.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.vw.formhandler.webspring.mvc.response.kuba.KubaServiceResponseErrorVO;
import com.vw.formhandler.webspring.mvc.response.leads.LeadsServiceResponseErrorVO;


/**
 * <p>Java class for errors complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="errors">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="error" type="{}error" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@SuppressWarnings("serial")
@XmlRootElement(name = "errors")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder = {
    "errors"
})
public class Errors implements FormHandlerResponseInterface 
{
	@XmlElementRefs({ 
        @XmlElementRef(name="validationError", type=ValidationError.class),
        @XmlElementRef(name="formHandlerError", type=FormHandlerError.class),
        @XmlElementRef(name="kubaServiceResponseError", type=KubaServiceResponseErrorVO.class),
        @XmlElementRef(name="leadsServiceResponseError", type=LeadsServiceResponseErrorVO.class)
	}) 
    private List<AbstractError> errors;

    /**
     * Gets the value of the error property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the error property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getError().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbstractError }
     * 
     * 
     */
    public List<AbstractError> getErrors() {
        if (errors == null) {
            errors = new ArrayList<AbstractError>();
        }
        return this.errors;
    }
}
